# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def recurFib n
	return 1 if n <= 2
	return (recurFib n-1) + (recurFib n-2)
end

def sumEvenFib n
	current_index = 1
	current_fib = recurFib current_index
	sum = 0
	while current_fib < n
		if current_fib % 2 == 0
			sum += current_fib
		end
		current_index += 1
		current_fib = recurFib current_index
	end
	return sum
end

n = gets.chomp.to_i
puts sumEvenFib n
