# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def iterFib(n):
    prev_fib = 1
    current_fib = 1
    for _a in range(n):
        next_fib = prev_fib + current_fib
        prev_fib = current_fib
        current_fib = next_fib
    return current_fib

result = 0
fib = 1
index = 0

while fib < 4000000:
    index += 1
    fib = iterFib(index)
    if fib % 2 == 0:
        result += fib

print result
